import type { Metadata } from 'next'
import { Rubik } from 'next/font/google'
import './globals.css'

//components
import Navbar from './components/Navbar'

const rubik = Rubik({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Demo App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={rubik.className}>
        <Navbar /> 
          {children}
      </body>
    </html>
  )
}
